stages:
  preprocess:
    cmd: python src/preprocess.py data/cell_samples_for_svm.csv data/train.csv  data/test.csv
    deps:
    - data/cell_samples_for_svm.csv
    - src/preprocess.py
    params:
    - preprocess.seed
    - preprocess.test_size
    outs:
    - data/train.csv
    - data/test.csv
    
  